app:
    resource: "@AppBundle/Controller/"
    type:     annotation
_default:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
_ing:
    path:     /ing/index
    defaults: { _controller: AppBundle:Ing:index }